![tower bridge](london.jpg)

London, or as the Romans called it "Londonium"! Home to [over 8.5 million residents](https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/bulletins/populationandhouseholdestimatesenglandandwales/census2021unroundeddata#population-and-household-estimates-england-and-wales-data) who speak over [300 languages](https://web.archive.org/web/20080924084621/http://www.cilt.org.uk/faqs/langspoken.htm). While the City of London is a little over one square mile (hence its nickname "The Square Mile"), Greater London has grown to encompass 32 boroughs spanning a total area of 606 square miles! 

![underground train leaving a platform](tube.jpg)

Given the city's roads were originally designed for horse and cart, this area and population growth has required the development of an efficient public transport system! Since the year 2000, this has been through the local government body called **Transport for London**, or *TfL*, which is managed by the London Mayor's office. Their remit covers the London Underground, Overground, Docklands Light Railway (DLR), buses, trams, river services (clipper and [Emirates Airline cable car](https://en.wikipedia.org/wiki/London_cable_car)), roads, and even taxis.

The Mayor of London's office make their data available to the public [here](https://data.london.gov.uk/dataset). In this project, you will work with a slightly modified version of a dataset containing information about public transport journey volume by transport type. 

The data has been loaded into a **Google BigQuery** database called `TFL` with a single table called `JOURNEYS`, including the following data:

## TFL.JOURNEYS

| Column | Definition | Data type |
|--------|------------|-----------|
| `MONTH`| Month in number format, e.g., `1` equals January | `INTEGER` |
| `YEAR` | Year | `INTEGER` |
| `DAYS` | Number of days in the given month | `INTEGER` |
| `REPORT_DATE` | Date that the data was reported | `DATE` |
| `JOURNEY_TYPE` | Method of transport used | `VARCHAR` |
| `JOURNEYS_MILLIONS` | Millions of journeys, measured in decimals | `FLOAT` |

Note that the table name is **upper case*** by default.

You will execute SQL queries to answer three questions, as listed in the instructions.

In [30]:
select * 
from TFL.JOURNEYS

     month  year  days report_date       journey_type  journeys_millions
0        2  2020    29  2020-06-30  Underground & DLR           8.041099
1        2  2020    29  2020-06-30                Bus          32.467243
2        2  2020    29  2020-06-30               Tram           0.470811
3        2  2020    29  2020-06-30         Overground           1.491890
4        2  2020    29  2020-06-30   Emirates Airline           0.004978
..     ...   ...   ...         ...                ...                ...
931      5  2012    31  2012-09-30                Bus         167.138336
932      5  2012    31  2012-09-30               Tram           2.328188
933      5  2012    31  2012-09-30         Overground          10.506406
934      5  2012    31  2012-09-30   Emirates Airline           0.534218
935      5  2012    31  2012-09-30           TfL Rail                NaN

[936 rows x 6 columns]

In [31]:
-- most_popular_transport_types
SELECT journey_type, SUM(journeys_millions) AS total_journeys_millions
FROM TFL.JOURNEYS
GROUP BY journey_type
ORDER BY total_journeys_millions DESC;

        journey_type  total_journeys_millions
0                Bus             24905.193947
1  Underground & DLR             15020.466544
2         Overground              1666.845666
3           TfL Rail               411.313421
4               Tram               314.689875
5   Emirates Airline                14.583718

In [32]:
SELECT month, 
	year, 
	ROUND(journeys_millions,2) AS rounded_journeys_millions
FROM TFL.JOURNEYS
WHERE journey_type = 'Emirates Airline' AND journeys_millions IS NOT NULL
ORDER BY rounded_journeys_millions DESC, year
LIMIT 5;

   month  year  rounded_journeys_millions
0      5  2012                       0.53
1      6  2012                       0.38
2      4  2012                       0.24
3      5  2013                       0.19
4      5  2015                       0.19

In [33]:
SELECT year,
	journey_type,
	SUM(journeys_millions) as total_journeys_millions
FROM TFL.JOURNEYS
WHERE journey_type LIKE '%Underground%'
GROUP BY year, journey_type
ORDER BY total_journeys_millions
LIMIT 5;

   year       journey_type  total_journeys_millions
0  2020  Underground & DLR               310.179316
1  2021  Underground & DLR               748.452544
2  2022  Underground & DLR              1064.859009
3  2010  Underground & DLR              1096.145588
4  2011  Underground & DLR              1156.647654